spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    datasource:
      url: jdbc:mysql://localhost:3306/dbname
      username:
      password:
    jpa:
      hibernate:
        ddl-auto: create
      database-platform: org.hibernate.dialect.PostegreSQLDialect
      show-sql: true
