spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://postgresql-tiphaine.alwaysdata.net/tiphaine_pokedex
    driver-class-name: org.postgresql.Driver
    username: tiphaine_spring
    password: $poimlk123
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
